#!/usr/bin/env python3
"""
Generates src/thunks_generated.cpp from the import inventory.

Every host-side symbol gets a stub that logs once and returns zero, so a
bring-up run tells you exactly which imports the engine actually reached and
in what order. You replace stubs with real implementations one at a time;
the dispatch table does not change.

Usage:  python tools/gen_thunks.py ../port_analysis/inventory.json src/thunks_generated.cpp
"""

import json
import sys
from collections import defaultdict

TIER_HINT = {
    'T0': 'scalars only',
    'T1': 'pointer in - translate the address',
    'T2': 'pointer out - write back through it',
    'T3': 'array of guest pointers - rebuild host-side',
    'T4': 'struct crosses the ABI - translate field by field',
    'T5': 'takes a guest callback - re-enters the JIT',
    'T6': 'varargs - format guest-side, cross a flat string',
}

GROUP_ORDER = ['OpenGL ES 2.0', 'EGL', 'Android NDK', 'FMOD Ex', 'pthread',
               'OS / syscalls', 'BSD sockets']

HEADER = '''// GENERATED by tools/gen_thunks.py - do not edit by hand.
//
// {total} host-side imports of libMBExpMobile.so. Each starts life as a stub
// that reports itself once and returns zero. Replace them in place; the table
// at the bottom is keyed by symbol name, so nothing else has to change.
//
// Tiers: T0 {t0} - T1 {t1} - T2 {t2} - T3 {t3} - T4 {t4} - T5 {t5} - T6 {t6}

#include <cstdio>

#include "env.h"

namespace wb {{
namespace {{

void stub(Env& e, const char* name) {{
  static thread_local const char* last = nullptr;
  if (last != name) {{
    std::printf("[stub] %s\\n", name);
    last = name;
  }}
  e.ret(0);
}}

'''

FOOTER = '''}}  // namespace

const ThunkEntry kThunkTable[] = {{
{entries}
}};

const std::size_t kThunkTableSize = sizeof(kThunkTable) / sizeof(kThunkTable[0]);

}}  // namespace wb
'''


def main():
    inv_path = sys.argv[1]
    out_path = sys.argv[2]
    inv = json.load(open(inv_path, encoding='utf-8'))
    host = [r for r in inv if r['place'] == 'HOST']

    tiers = defaultdict(int)
    for r in host:
        tiers[r['tier']] += 1

    by_group = defaultdict(list)
    for r in host:
        by_group[r['group']].append(r)

    out = [HEADER.format(total=len(host),
                         t0=tiers['T0'], t1=tiers['T1'], t2=tiers['T2'],
                         t3=tiers['T3'], t4=tiers['T4'], t5=tiers['T5'],
                         t6=tiers['T6'])]

    entries = []
    groups = [g for g in GROUP_ORDER if g in by_group]
    groups += [g for g in sorted(by_group) if g not in GROUP_ORDER]

    for g in groups:
        rows = sorted(by_group[g], key=lambda r: (r['tier'], r['sym']))
        out.append('// %s\n// %s\n' % (g, '-' * (72 - len(g))))
        for r in rows:
            hint = TIER_HINT.get(r['tier'], '')
            sig = r['sig']
            if sig != r['sym']:
                out.append('// %s\n' % sig)
            out.append('// %s: %s\n' % (r['tier'], hint))
            out.append('void t_%s(Env& e) { stub(e, "%s"); }\n\n'
                       % (r['sym'], r['sym']))
            entries.append('    {"%s", &t_%s},' % (r['sym'], r['sym']))
        out.append('\n')

    out.append(FOOTER.format(entries='\n'.join(entries)))
    open(out_path, 'w', encoding='utf-8').write(''.join(out))
    print('wrote %s: %d thunks across %d groups'
          % (out_path, len(host), len(groups)))
    for g in groups:
        print('   %-26s %d' % (g, len(by_group[g])))


if __name__ == '__main__':
    main()
