// GENERATED by tools/gen_thunks.py - do not edit by hand.
//
// 221 host-side imports of libMBExpMobile.so. Each starts life as a stub
// that reports itself once and returns zero. Replace them in place; the table
// at the bottom is keyed by symbol name, so nothing else has to change.
//
// Tiers: T0 111 - T1 24 - T2 53 - T3 1 - T4 28 - T5 3 - T6 1

#include <cstdio>

#include "env.h"

namespace wb {
namespace {

void stub(Env& e, const char* name) {
  static thread_local const char* last = nullptr;
  if (last != name) {
    std::printf("[stub] %s\n", name);
    last = name;
  }
  e.ret(0);
}

// OpenGL ES 2.0
// -----------------------------------------------------------
// T0: scalars only
void t_glActiveTexture(Env& e) { stub(e, "glActiveTexture"); }

// T0: scalars only
void t_glAttachShader(Env& e) { stub(e, "glAttachShader"); }

// T0: scalars only
void t_glBindBuffer(Env& e) { stub(e, "glBindBuffer"); }

// T0: scalars only
void t_glBindFramebuffer(Env& e) { stub(e, "glBindFramebuffer"); }

// T0: scalars only
void t_glBindRenderbuffer(Env& e) { stub(e, "glBindRenderbuffer"); }

// T0: scalars only
void t_glBindTexture(Env& e) { stub(e, "glBindTexture"); }

// T0: scalars only
void t_glBlendEquation(Env& e) { stub(e, "glBlendEquation"); }

// T0: scalars only
void t_glBlendFunc(Env& e) { stub(e, "glBlendFunc"); }

// T0: scalars only
void t_glClear(Env& e) { stub(e, "glClear"); }

// T0: scalars only
void t_glClearColor(Env& e) { stub(e, "glClearColor"); }

// T0: scalars only
void t_glCompileShader(Env& e) { stub(e, "glCompileShader"); }

// T0: scalars only
void t_glCreateProgram(Env& e) { stub(e, "glCreateProgram"); }

// T0: scalars only
void t_glCreateShader(Env& e) { stub(e, "glCreateShader"); }

// T0: scalars only
void t_glCullFace(Env& e) { stub(e, "glCullFace"); }

// T0: scalars only
void t_glDeleteProgram(Env& e) { stub(e, "glDeleteProgram"); }

// T0: scalars only
void t_glDeleteShader(Env& e) { stub(e, "glDeleteShader"); }

// T0: scalars only
void t_glDepthFunc(Env& e) { stub(e, "glDepthFunc"); }

// T0: scalars only
void t_glDepthMask(Env& e) { stub(e, "glDepthMask"); }

// T0: scalars only
void t_glDisable(Env& e) { stub(e, "glDisable"); }

// T0: scalars only
void t_glDrawArrays(Env& e) { stub(e, "glDrawArrays"); }

// T0: scalars only
void t_glEnable(Env& e) { stub(e, "glEnable"); }

// T0: scalars only
void t_glEnableVertexAttribArray(Env& e) { stub(e, "glEnableVertexAttribArray"); }

// T0: scalars only
void t_glFramebufferRenderbuffer(Env& e) { stub(e, "glFramebufferRenderbuffer"); }

// T0: scalars only
void t_glFramebufferTexture2D(Env& e) { stub(e, "glFramebufferTexture2D"); }

// T0: scalars only
void t_glGenerateMipmap(Env& e) { stub(e, "glGenerateMipmap"); }

// T0: scalars only
void t_glLinkProgram(Env& e) { stub(e, "glLinkProgram"); }

// T0: scalars only
void t_glPixelStorei(Env& e) { stub(e, "glPixelStorei"); }

// T0: scalars only
void t_glRenderbufferStorage(Env& e) { stub(e, "glRenderbufferStorage"); }

// T0: scalars only
void t_glScissor(Env& e) { stub(e, "glScissor"); }

// T0: scalars only
void t_glTexParameterf(Env& e) { stub(e, "glTexParameterf"); }

// T0: scalars only
void t_glTexParameteri(Env& e) { stub(e, "glTexParameteri"); }

// T0: scalars only
void t_glUniform1f(Env& e) { stub(e, "glUniform1f"); }

// T0: scalars only
void t_glUniform1i(Env& e) { stub(e, "glUniform1i"); }

// T0: scalars only
void t_glUseProgram(Env& e) { stub(e, "glUseProgram"); }

// T0: scalars only
void t_glViewport(Env& e) { stub(e, "glViewport"); }

// T1: pointer in - translate the address
void t_glBufferData(Env& e) { stub(e, "glBufferData"); }

// T1: pointer in - translate the address
void t_glCompressedTexImage2D(Env& e) { stub(e, "glCompressedTexImage2D"); }

// T1: pointer in - translate the address
void t_glDeleteBuffers(Env& e) { stub(e, "glDeleteBuffers"); }

// T1: pointer in - translate the address
void t_glDeleteFramebuffers(Env& e) { stub(e, "glDeleteFramebuffers"); }

// T1: pointer in - translate the address
void t_glDeleteRenderbuffers(Env& e) { stub(e, "glDeleteRenderbuffers"); }

// T1: pointer in - translate the address
void t_glDeleteTextures(Env& e) { stub(e, "glDeleteTextures"); }

// T1: pointer in - translate the address
void t_glDrawElements(Env& e) { stub(e, "glDrawElements"); }

// T1: pointer in - translate the address
void t_glGetAttribLocation(Env& e) { stub(e, "glGetAttribLocation"); }

// T1: pointer in - translate the address
void t_glGetUniformLocation(Env& e) { stub(e, "glGetUniformLocation"); }

// T1: pointer in - translate the address
void t_glTexImage2D(Env& e) { stub(e, "glTexImage2D"); }

// T1: pointer in - translate the address
void t_glUniform1iv(Env& e) { stub(e, "glUniform1iv"); }

// T1: pointer in - translate the address
void t_glUniform4fv(Env& e) { stub(e, "glUniform4fv"); }

// T1: pointer in - translate the address
void t_glUniformMatrix4fv(Env& e) { stub(e, "glUniformMatrix4fv"); }

// T1: pointer in - translate the address
void t_glVertexAttribPointer(Env& e) { stub(e, "glVertexAttribPointer"); }

// T2: pointer out - write back through it
void t_glGenBuffers(Env& e) { stub(e, "glGenBuffers"); }

// T2: pointer out - write back through it
void t_glGenFramebuffers(Env& e) { stub(e, "glGenFramebuffers"); }

// T2: pointer out - write back through it
void t_glGenRenderbuffers(Env& e) { stub(e, "glGenRenderbuffers"); }

// T2: pointer out - write back through it
void t_glGenTextures(Env& e) { stub(e, "glGenTextures"); }

// T2: pointer out - write back through it
void t_glGetFloatv(Env& e) { stub(e, "glGetFloatv"); }

// T2: pointer out - write back through it
void t_glGetIntegerv(Env& e) { stub(e, "glGetIntegerv"); }

// T2: pointer out - write back through it
void t_glGetProgramInfoLog(Env& e) { stub(e, "glGetProgramInfoLog"); }

// T2: pointer out - write back through it
void t_glGetProgramiv(Env& e) { stub(e, "glGetProgramiv"); }

// T2: pointer out - write back through it
void t_glGetShaderInfoLog(Env& e) { stub(e, "glGetShaderInfoLog"); }

// T2: pointer out - write back through it
void t_glGetShaderiv(Env& e) { stub(e, "glGetShaderiv"); }

// T3: array of guest pointers - rebuild host-side
void t_glShaderSource(Env& e) { stub(e, "glShaderSource"); }


// EGL
// ---------------------------------------------------------------------
// T0: scalars only
void t_eglDestroyContext(Env& e) { stub(e, "eglDestroyContext"); }

// T0: scalars only
void t_eglDestroySurface(Env& e) { stub(e, "eglDestroySurface"); }

// T0: scalars only
void t_eglGetDisplay(Env& e) { stub(e, "eglGetDisplay"); }

// T0: scalars only
void t_eglMakeCurrent(Env& e) { stub(e, "eglMakeCurrent"); }

// T0: scalars only
void t_eglSwapBuffers(Env& e) { stub(e, "eglSwapBuffers"); }

// T0: scalars only
void t_eglTerminate(Env& e) { stub(e, "eglTerminate"); }

// T1: pointer in - translate the address
void t_eglCreateContext(Env& e) { stub(e, "eglCreateContext"); }

// T1: pointer in - translate the address
void t_eglCreateWindowSurface(Env& e) { stub(e, "eglCreateWindowSurface"); }

// T2: pointer out - write back through it
void t_eglGetConfigAttrib(Env& e) { stub(e, "eglGetConfigAttrib"); }

// T2: pointer out - write back through it
void t_eglGetConfigs(Env& e) { stub(e, "eglGetConfigs"); }

// T2: pointer out - write back through it
void t_eglInitialize(Env& e) { stub(e, "eglInitialize"); }

// T2: pointer out - write back through it
void t_eglQuerySurface(Env& e) { stub(e, "eglQuerySurface"); }


// Android NDK
// -------------------------------------------------------------
// T0: scalars only
void t_AConfiguration_delete(Env& e) { stub(e, "AConfiguration_delete"); }

// T0: scalars only
void t_AConfiguration_fromAssetManager(Env& e) { stub(e, "AConfiguration_fromAssetManager"); }

// T0: scalars only
void t_AConfiguration_getCountry(Env& e) { stub(e, "AConfiguration_getCountry"); }

// T0: scalars only
void t_AConfiguration_getDensity(Env& e) { stub(e, "AConfiguration_getDensity"); }

// T0: scalars only
void t_AConfiguration_getKeyboard(Env& e) { stub(e, "AConfiguration_getKeyboard"); }

// T0: scalars only
void t_AConfiguration_getKeysHidden(Env& e) { stub(e, "AConfiguration_getKeysHidden"); }

// T0: scalars only
void t_AConfiguration_getLanguage(Env& e) { stub(e, "AConfiguration_getLanguage"); }

// T0: scalars only
void t_AConfiguration_getMcc(Env& e) { stub(e, "AConfiguration_getMcc"); }

// T0: scalars only
void t_AConfiguration_getMnc(Env& e) { stub(e, "AConfiguration_getMnc"); }

// T0: scalars only
void t_AConfiguration_getNavHidden(Env& e) { stub(e, "AConfiguration_getNavHidden"); }

// T0: scalars only
void t_AConfiguration_getNavigation(Env& e) { stub(e, "AConfiguration_getNavigation"); }

// T0: scalars only
void t_AConfiguration_getOrientation(Env& e) { stub(e, "AConfiguration_getOrientation"); }

// T0: scalars only
void t_AConfiguration_getScreenLong(Env& e) { stub(e, "AConfiguration_getScreenLong"); }

// T0: scalars only
void t_AConfiguration_getScreenSize(Env& e) { stub(e, "AConfiguration_getScreenSize"); }

// T0: scalars only
void t_AConfiguration_getSdkVersion(Env& e) { stub(e, "AConfiguration_getSdkVersion"); }

// T0: scalars only
void t_AConfiguration_getTouchscreen(Env& e) { stub(e, "AConfiguration_getTouchscreen"); }

// T0: scalars only
void t_AConfiguration_getUiModeNight(Env& e) { stub(e, "AConfiguration_getUiModeNight"); }

// T0: scalars only
void t_AConfiguration_getUiModeType(Env& e) { stub(e, "AConfiguration_getUiModeType"); }

// T0: scalars only
void t_AConfiguration_new(Env& e) { stub(e, "AConfiguration_new"); }

// T0: scalars only
void t_AInputEvent_getSource(Env& e) { stub(e, "AInputEvent_getSource"); }

// T0: scalars only
void t_AInputEvent_getType(Env& e) { stub(e, "AInputEvent_getType"); }

// T0: scalars only
void t_AKeyEvent_getAction(Env& e) { stub(e, "AKeyEvent_getAction"); }

// T0: scalars only
void t_AKeyEvent_getKeyCode(Env& e) { stub(e, "AKeyEvent_getKeyCode"); }

// T0: scalars only
void t_ALooper_pollAll(Env& e) { stub(e, "ALooper_pollAll"); }

// T0: scalars only
void t_ALooper_prepare(Env& e) { stub(e, "ALooper_prepare"); }

// T0: scalars only
void t_AMotionEvent_getAction(Env& e) { stub(e, "AMotionEvent_getAction"); }

// T0: scalars only
void t_AMotionEvent_getAxisValue(Env& e) { stub(e, "AMotionEvent_getAxisValue"); }

// T0: scalars only
void t_AMotionEvent_getPointerCount(Env& e) { stub(e, "AMotionEvent_getPointerCount"); }

// T0: scalars only
void t_AMotionEvent_getPointerId(Env& e) { stub(e, "AMotionEvent_getPointerId"); }

// T0: scalars only
void t_AMotionEvent_getX(Env& e) { stub(e, "AMotionEvent_getX"); }

// T0: scalars only
void t_AMotionEvent_getY(Env& e) { stub(e, "AMotionEvent_getY"); }

// T0: scalars only
void t_ANativeActivity_finish(Env& e) { stub(e, "ANativeActivity_finish"); }

// T0: scalars only
void t_ANativeWindow_getHeight(Env& e) { stub(e, "ANativeWindow_getHeight"); }

// T0: scalars only
void t_ANativeWindow_getWidth(Env& e) { stub(e, "ANativeWindow_getWidth"); }

// T0: scalars only
void t_ANativeWindow_setBuffersGeometry(Env& e) { stub(e, "ANativeWindow_setBuffersGeometry"); }

// T0: scalars only
void t_AStorageManager_delete(Env& e) { stub(e, "AStorageManager_delete"); }

// T0: scalars only
void t_AStorageManager_isObbMounted(Env& e) { stub(e, "AStorageManager_isObbMounted"); }

// T0: scalars only
void t_AStorageManager_new(Env& e) { stub(e, "AStorageManager_new"); }

// T0: scalars only
void t_AStorageManager_unmountObb(Env& e) { stub(e, "AStorageManager_unmountObb"); }

// T0: scalars only
void t_nv_android_init(Env& e) { stub(e, "nv_android_init"); }

// T1: pointer in - translate the address
void t_AStorageManager_getMountedObbPath(Env& e) { stub(e, "AStorageManager_getMountedObbPath"); }

// T1: pointer in - translate the address
void t_AStorageManager_mountObb(Env& e) { stub(e, "AStorageManager_mountObb"); }

// T2: pointer out - write back through it
void t_AInputQueue_attachLooper(Env& e) { stub(e, "AInputQueue_attachLooper"); }

// T2: pointer out - write back through it
void t_AInputQueue_detachLooper(Env& e) { stub(e, "AInputQueue_detachLooper"); }

// T2: pointer out - write back through it
void t_AInputQueue_finishEvent(Env& e) { stub(e, "AInputQueue_finishEvent"); }

// T2: pointer out - write back through it
void t_AInputQueue_getEvent(Env& e) { stub(e, "AInputQueue_getEvent"); }

// T2: pointer out - write back through it
void t_AInputQueue_preDispatchEvent(Env& e) { stub(e, "AInputQueue_preDispatchEvent"); }

// T5: takes a guest callback - re-enters the JIT
void t_ALooper_addFd(Env& e) { stub(e, "ALooper_addFd"); }

// T6: varargs - format guest-side, cross a flat string
void t___android_log_print(Env& e) { stub(e, "__android_log_print"); }


// FMOD Ex
// -----------------------------------------------------------------
// T0: scalars only
void t_FMOD_System_Create(Env& e) { stub(e, "FMOD_System_Create"); }

// FMOD::Sound::setDefaults(float, float, float, int)
// T0: scalars only
void t__ZN4FMOD5Sound11setDefaultsEfffi(Env& e) { stub(e, "_ZN4FMOD5Sound11setDefaultsEfffi"); }

// FMOD::Sound::set3DMinMaxDistance(float, float)
// T0: scalars only
void t__ZN4FMOD5Sound19set3DMinMaxDistanceEff(Env& e) { stub(e, "_ZN4FMOD5Sound19set3DMinMaxDistanceEff"); }

// FMOD::Sound::release()
// T0: scalars only
void t__ZN4FMOD5Sound7releaseEv(Env& e) { stub(e, "_ZN4FMOD5Sound7releaseEv"); }

// FMOD::System::set3DSettings(float, float, float)
// T0: scalars only
void t__ZN4FMOD6System13set3DSettingsEfff(Env& e) { stub(e, "_ZN4FMOD6System13set3DSettingsEfff"); }

// FMOD::System::setSpeakerMode(FMOD_SPEAKERMODE)
// T0: scalars only
void t__ZN4FMOD6System14setSpeakerModeE16FMOD_SPEAKERMODE(Env& e) { stub(e, "_ZN4FMOD6System14setSpeakerModeE16FMOD_SPEAKERMODE"); }

// FMOD::System::setDSPBufferSize(unsigned int, int)
// T0: scalars only
void t__ZN4FMOD6System16setDSPBufferSizeEji(Env& e) { stub(e, "_ZN4FMOD6System16setDSPBufferSizeEji"); }

// FMOD::System::setSoftwareFormat(int, FMOD_SOUND_FORMAT, int, int, FMOD_DSP_RESAMPLER)
// T0: scalars only
void t__ZN4FMOD6System17setSoftwareFormatEi17FMOD_SOUND_FORMATii18FMOD_DSP_RESAMPLER(Env& e) { stub(e, "_ZN4FMOD6System17setSoftwareFormatEi17FMOD_SOUND_FORMATii18FMOD_DSP_RESAMPLER"); }

// FMOD::System::setHardwareChannels(int)
// T0: scalars only
void t__ZN4FMOD6System19setHardwareChannelsEi(Env& e) { stub(e, "_ZN4FMOD6System19setHardwareChannelsEi"); }

// FMOD::System::close()
// T0: scalars only
void t__ZN4FMOD6System5closeEv(Env& e) { stub(e, "_ZN4FMOD6System5closeEv"); }

// FMOD::System::update()
// T0: scalars only
void t__ZN4FMOD6System6updateEv(Env& e) { stub(e, "_ZN4FMOD6System6updateEv"); }

// FMOD::System::setOutput(FMOD_OUTPUTTYPE)
// T0: scalars only
void t__ZN4FMOD6System9setOutputE15FMOD_OUTPUTTYPE(Env& e) { stub(e, "_ZN4FMOD6System9setOutputE15FMOD_OUTPUTTYPE"); }

// FMOD::Channel::setPosition(unsigned int, unsigned int)
// T0: scalars only
void t__ZN4FMOD7Channel11setPositionEjj(Env& e) { stub(e, "_ZN4FMOD7Channel11setPositionEjj"); }

// FMOD::Channel::setPriority(int)
// T0: scalars only
void t__ZN4FMOD7Channel11setPriorityEi(Env& e) { stub(e, "_ZN4FMOD7Channel11setPriorityEi"); }

// FMOD::Channel::setFrequency(float)
// T0: scalars only
void t__ZN4FMOD7Channel12setFrequencyEf(Env& e) { stub(e, "_ZN4FMOD7Channel12setFrequencyEf"); }

// FMOD::Channel::stop()
// T0: scalars only
void t__ZN4FMOD7Channel4stopEv(Env& e) { stub(e, "_ZN4FMOD7Channel4stopEv"); }

// FMOD::Channel::setMode(unsigned int)
// T0: scalars only
void t__ZN4FMOD7Channel7setModeEj(Env& e) { stub(e, "_ZN4FMOD7Channel7setModeEj"); }

// FMOD::Channel::setPaused(bool)
// T0: scalars only
void t__ZN4FMOD7Channel9setPausedEb(Env& e) { stub(e, "_ZN4FMOD7Channel9setPausedEb"); }

// FMOD::Channel::setVolume(float)
// T0: scalars only
void t__ZN4FMOD7Channel9setVolumeEf(Env& e) { stub(e, "_ZN4FMOD7Channel9setVolumeEf"); }

// FMOD::Sound::getDefaults(float*, float*, float*, int*)
// T2: pointer out - write back through it
void t__ZN4FMOD5Sound11getDefaultsEPfS1_S1_Pi(Env& e) { stub(e, "_ZN4FMOD5Sound11getDefaultsEPfS1_S1_Pi"); }

// FMOD::Sound::getOpenState(FMOD_OPENSTATE*, unsigned int*, bool*, bool*)
// T2: pointer out - write back through it
void t__ZN4FMOD5Sound12getOpenStateEP14FMOD_OPENSTATEPjPbS4_(Env& e) { stub(e, "_ZN4FMOD5Sound12getOpenStateEP14FMOD_OPENSTATEPjPbS4_"); }

// FMOD::Sound::getLength(unsigned int*, unsigned int)
// T2: pointer out - write back through it
void t__ZN4FMOD5Sound9getLengthEPjj(Env& e) { stub(e, "_ZN4FMOD5Sound9getLengthEPjj"); }

// FMOD::System::getChannel(int, FMOD::Channel**)
// T2: pointer out - write back through it
void t__ZN4FMOD6System10getChannelEiPPNS_7ChannelE(Env& e) { stub(e, "_ZN4FMOD6System10getChannelEiPPNS_7ChannelE"); }

// FMOD::System::getDriverCaps(int, unsigned int*, int*, FMOD_SPEAKERMODE*)
// T2: pointer out - write back through it
void t__ZN4FMOD6System13getDriverCapsEiPjPiP16FMOD_SPEAKERMODE(Env& e) { stub(e, "_ZN4FMOD6System13getDriverCapsEiPjPiP16FMOD_SPEAKERMODE"); }

// FMOD::System::getNumDrivers(int*)
// T2: pointer out - write back through it
void t__ZN4FMOD6System13getNumDriversEPi(Env& e) { stub(e, "_ZN4FMOD6System13getNumDriversEPi"); }

// FMOD::System::getChannelsPlaying(int*)
// T2: pointer out - write back through it
void t__ZN4FMOD6System18getChannelsPlayingEPi(Env& e) { stub(e, "_ZN4FMOD6System18getChannelsPlayingEPi"); }

// FMOD::System::init(int, unsigned int, void*)
// T2: pointer out - write back through it
void t__ZN4FMOD6System4initEijPv(Env& e) { stub(e, "_ZN4FMOD6System4initEijPv"); }

// FMOD::System::playSound(FMOD_CHANNELINDEX, FMOD::Sound*, bool, FMOD::Channel**)
// T2: pointer out - write back through it
void t__ZN4FMOD6System9playSoundE17FMOD_CHANNELINDEXPNS_5SoundEbPPNS_7ChannelE(Env& e) { stub(e, "_ZN4FMOD6System9playSoundE17FMOD_CHANNELINDEXPNS_5SoundEbPPNS_7ChannelE"); }

// FMOD::Channel::getPosition(unsigned int*, unsigned int)
// T2: pointer out - write back through it
void t__ZN4FMOD7Channel11getPositionEPjj(Env& e) { stub(e, "_ZN4FMOD7Channel11getPositionEPjj"); }

// FMOD::Channel::getUserData(void**)
// T2: pointer out - write back through it
void t__ZN4FMOD7Channel11getUserDataEPPv(Env& e) { stub(e, "_ZN4FMOD7Channel11getUserDataEPPv"); }

// FMOD::Channel::setUserData(void*)
// T2: pointer out - write back through it
void t__ZN4FMOD7Channel11setUserDataEPv(Env& e) { stub(e, "_ZN4FMOD7Channel11setUserDataEPv"); }

// FMOD::Channel::getMode(unsigned int*)
// T2: pointer out - write back through it
void t__ZN4FMOD7Channel7getModeEPj(Env& e) { stub(e, "_ZN4FMOD7Channel7getModeEPj"); }

// FMOD::Channel::getIndex(int*)
// T2: pointer out - write back through it
void t__ZN4FMOD7Channel8getIndexEPi(Env& e) { stub(e, "_ZN4FMOD7Channel8getIndexEPi"); }

// FMOD::Channel::getVolume(float*)
// T2: pointer out - write back through it
void t__ZN4FMOD7Channel9getVolumeEPf(Env& e) { stub(e, "_ZN4FMOD7Channel9getVolumeEPf"); }

// FMOD::Channel::isPlaying(bool*)
// T2: pointer out - write back through it
void t__ZN4FMOD7Channel9isPlayingEPb(Env& e) { stub(e, "_ZN4FMOD7Channel9isPlayingEPb"); }

// FMOD::System::createSound(char const*, unsigned int, FMOD_CREATESOUNDEXINFO*, FMOD::Sound**)
// T4: struct crosses the ABI - translate field by field
void t__ZN4FMOD6System11createSoundEPKcjP22FMOD_CREATESOUNDEXINFOPPNS_5SoundE(Env& e) { stub(e, "_ZN4FMOD6System11createSoundEPKcjP22FMOD_CREATESOUNDEXINFOPPNS_5SoundE"); }

// FMOD::System::createStream(char const*, unsigned int, FMOD_CREATESOUNDEXINFO*, FMOD::Sound**)
// T4: struct crosses the ABI - translate field by field
void t__ZN4FMOD6System12createStreamEPKcjP22FMOD_CREATESOUNDEXINFOPPNS_5SoundE(Env& e) { stub(e, "_ZN4FMOD6System12createStreamEPKcjP22FMOD_CREATESOUNDEXINFOPPNS_5SoundE"); }

// FMOD::System::getDriverInfo(int, char*, int, FMOD_GUID*)
// T4: struct crosses the ABI - translate field by field
void t__ZN4FMOD6System13getDriverInfoEiPciP9FMOD_GUID(Env& e) { stub(e, "_ZN4FMOD6System13getDriverInfoEiPciP9FMOD_GUID"); }

// FMOD::System::set3DListenerAttributes(int, FMOD_VECTOR const*, FMOD_VECTOR const*, FMOD_VECTOR const*, FMOD_VECTOR const*)
// T4: struct crosses the ABI - translate field by field
void t__ZN4FMOD6System23set3DListenerAttributesEiPK11FMOD_VECTORS3_S3_S3_(Env& e) { stub(e, "_ZN4FMOD6System23set3DListenerAttributesEiPK11FMOD_VECTORS3_S3_S3_"); }

// FMOD::Channel::set3DAttributes(FMOD_VECTOR const*, FMOD_VECTOR const*)
// T4: struct crosses the ABI - translate field by field
void t__ZN4FMOD7Channel15set3DAttributesEPK11FMOD_VECTORS3_(Env& e) { stub(e, "_ZN4FMOD7Channel15set3DAttributesEPK11FMOD_VECTORS3_"); }

// FMOD::Channel::setCallback(FMOD_RESULT(*)(FMOD_CHANNEL*, FMOD_CHANNEL_CALLBACKTYPE, void*, void*))
// T5: takes a guest callback - re-enters the JIT
void t__ZN4FMOD7Channel11setCallbackEPF11FMOD_RESULTP12FMOD_CHANNEL25FMOD_CHANNEL_CALLBACKTYPEPvS5_E(Env& e) { stub(e, "_ZN4FMOD7Channel11setCallbackEPF11FMOD_RESULTP12FMOD_CHANNEL25FMOD_CHANNEL_CALLBACKTYPEPvS5_E"); }


// pthread
// -----------------------------------------------------------------
// T2: pointer out - write back through it
void t_pthread_attr_init(Env& e) { stub(e, "pthread_attr_init"); }

// T2: pointer out - write back through it
void t_pthread_attr_setdetachstate(Env& e) { stub(e, "pthread_attr_setdetachstate"); }

// T2: pointer out - write back through it
void t_pthread_cond_broadcast(Env& e) { stub(e, "pthread_cond_broadcast"); }

// T2: pointer out - write back through it
void t_pthread_cond_destroy(Env& e) { stub(e, "pthread_cond_destroy"); }

// T2: pointer out - write back through it
void t_pthread_cond_init(Env& e) { stub(e, "pthread_cond_init"); }

// T2: pointer out - write back through it
void t_pthread_cond_signal(Env& e) { stub(e, "pthread_cond_signal"); }

// T2: pointer out - write back through it
void t_pthread_cond_wait(Env& e) { stub(e, "pthread_cond_wait"); }

// T2: pointer out - write back through it
void t_pthread_join(Env& e) { stub(e, "pthread_join"); }

// T2: pointer out - write back through it
void t_pthread_kill(Env& e) { stub(e, "pthread_kill"); }

// T2: pointer out - write back through it
void t_pthread_mutex_destroy(Env& e) { stub(e, "pthread_mutex_destroy"); }

// T2: pointer out - write back through it
void t_pthread_mutex_init(Env& e) { stub(e, "pthread_mutex_init"); }

// T2: pointer out - write back through it
void t_pthread_mutex_lock(Env& e) { stub(e, "pthread_mutex_lock"); }

// T2: pointer out - write back through it
void t_pthread_mutex_trylock(Env& e) { stub(e, "pthread_mutex_trylock"); }

// T2: pointer out - write back through it
void t_pthread_mutex_unlock(Env& e) { stub(e, "pthread_mutex_unlock"); }

// T2: pointer out - write back through it
void t_pthread_mutexattr_init(Env& e) { stub(e, "pthread_mutexattr_init"); }

// T2: pointer out - write back through it
void t_pthread_mutexattr_settype(Env& e) { stub(e, "pthread_mutexattr_settype"); }

// T4: struct crosses the ABI - translate field by field
void t_pthread_cond_timedwait(Env& e) { stub(e, "pthread_cond_timedwait"); }

// T5: takes a guest callback - re-enters the JIT
void t_pthread_create(Env& e) { stub(e, "pthread_create"); }


// OS / syscalls
// -----------------------------------------------------------
// T0: scalars only
void t_alarm(Env& e) { stub(e, "alarm"); }

// T0: scalars only
void t_close(Env& e) { stub(e, "close"); }

// T0: scalars only
void t_fcntl(Env& e) { stub(e, "fcntl"); }

// T0: scalars only
void t_geteuid(Env& e) { stub(e, "geteuid"); }

// T0: scalars only
void t_ioctl(Env& e) { stub(e, "ioctl"); }

// T0: scalars only
void t_lseek(Env& e) { stub(e, "lseek"); }

// T0: scalars only
void t_pipe(Env& e) { stub(e, "pipe"); }

// T0: scalars only
void t_syscall(Env& e) { stub(e, "syscall"); }

// T0: scalars only
void t_time(Env& e) { stub(e, "time"); }

// T0: scalars only
void t_usleep(Env& e) { stub(e, "usleep"); }

// T1: pointer in - translate the address
void t_getenv(Env& e) { stub(e, "getenv"); }

// T1: pointer in - translate the address
void t_mkdir(Env& e) { stub(e, "mkdir"); }

// T1: pointer in - translate the address
void t_open(Env& e) { stub(e, "open"); }

// T1: pointer in - translate the address
void t_read(Env& e) { stub(e, "read"); }

// T1: pointer in - translate the address
void t_write(Env& e) { stub(e, "write"); }

// T1: pointer in - translate the address
void t_writev(Env& e) { stub(e, "writev"); }

// T4: struct crosses the ABI - translate field by field
void t_clock_gettime(Env& e) { stub(e, "clock_gettime"); }

// T4: struct crosses the ABI - translate field by field
void t_fstat(Env& e) { stub(e, "fstat"); }

// T4: struct crosses the ABI - translate field by field
void t_getpwuid(Env& e) { stub(e, "getpwuid"); }

// T4: struct crosses the ABI - translate field by field
void t_gettimeofday(Env& e) { stub(e, "gettimeofday"); }

// T4: struct crosses the ABI - translate field by field
void t_poll(Env& e) { stub(e, "poll"); }

// T4: struct crosses the ABI - translate field by field
void t_sigaction(Env& e) { stub(e, "sigaction"); }

// T4: struct crosses the ABI - translate field by field
void t_stat(Env& e) { stub(e, "stat"); }


// BSD sockets
// -------------------------------------------------------------
// T0: scalars only
void t_socket(Env& e) { stub(e, "socket"); }

// T2: pointer out - write back through it
void t_inet_aton(Env& e) { stub(e, "inet_aton"); }

// T2: pointer out - write back through it
void t_inet_ntoa(Env& e) { stub(e, "inet_ntoa"); }

// T4: struct crosses the ABI - translate field by field
void t_bind(Env& e) { stub(e, "bind"); }

// T4: struct crosses the ABI - translate field by field
void t_connect(Env& e) { stub(e, "connect"); }

// T4: struct crosses the ABI - translate field by field
void t_freeaddrinfo(Env& e) { stub(e, "freeaddrinfo"); }

// T4: struct crosses the ABI - translate field by field
void t_getaddrinfo(Env& e) { stub(e, "getaddrinfo"); }

// T4: struct crosses the ABI - translate field by field
void t_gethostbyaddr(Env& e) { stub(e, "gethostbyaddr"); }

// T4: struct crosses the ABI - translate field by field
void t_gethostbyname(Env& e) { stub(e, "gethostbyname"); }

// T4: struct crosses the ABI - translate field by field
void t_getpeername(Env& e) { stub(e, "getpeername"); }

// T4: struct crosses the ABI - translate field by field
void t_getsockname(Env& e) { stub(e, "getsockname"); }

// T4: struct crosses the ABI - translate field by field
void t_getsockopt(Env& e) { stub(e, "getsockopt"); }

// T4: struct crosses the ABI - translate field by field
void t_recv(Env& e) { stub(e, "recv"); }

// T4: struct crosses the ABI - translate field by field
void t_recvmsg(Env& e) { stub(e, "recvmsg"); }

// T4: struct crosses the ABI - translate field by field
void t_select(Env& e) { stub(e, "select"); }

// T4: struct crosses the ABI - translate field by field
void t_send(Env& e) { stub(e, "send"); }

// T4: struct crosses the ABI - translate field by field
void t_sendmsg(Env& e) { stub(e, "sendmsg"); }

// T4: struct crosses the ABI - translate field by field
void t_setsockopt(Env& e) { stub(e, "setsockopt"); }


}  // namespace

const ThunkEntry kThunkTable[] = {
    {"glActiveTexture", &t_glActiveTexture},
    {"glAttachShader", &t_glAttachShader},
    {"glBindBuffer", &t_glBindBuffer},
    {"glBindFramebuffer", &t_glBindFramebuffer},
    {"glBindRenderbuffer", &t_glBindRenderbuffer},
    {"glBindTexture", &t_glBindTexture},
    {"glBlendEquation", &t_glBlendEquation},
    {"glBlendFunc", &t_glBlendFunc},
    {"glClear", &t_glClear},
    {"glClearColor", &t_glClearColor},
    {"glCompileShader", &t_glCompileShader},
    {"glCreateProgram", &t_glCreateProgram},
    {"glCreateShader", &t_glCreateShader},
    {"glCullFace", &t_glCullFace},
    {"glDeleteProgram", &t_glDeleteProgram},
    {"glDeleteShader", &t_glDeleteShader},
    {"glDepthFunc", &t_glDepthFunc},
    {"glDepthMask", &t_glDepthMask},
    {"glDisable", &t_glDisable},
    {"glDrawArrays", &t_glDrawArrays},
    {"glEnable", &t_glEnable},
    {"glEnableVertexAttribArray", &t_glEnableVertexAttribArray},
    {"glFramebufferRenderbuffer", &t_glFramebufferRenderbuffer},
    {"glFramebufferTexture2D", &t_glFramebufferTexture2D},
    {"glGenerateMipmap", &t_glGenerateMipmap},
    {"glLinkProgram", &t_glLinkProgram},
    {"glPixelStorei", &t_glPixelStorei},
    {"glRenderbufferStorage", &t_glRenderbufferStorage},
    {"glScissor", &t_glScissor},
    {"glTexParameterf", &t_glTexParameterf},
    {"glTexParameteri", &t_glTexParameteri},
    {"glUniform1f", &t_glUniform1f},
    {"glUniform1i", &t_glUniform1i},
    {"glUseProgram", &t_glUseProgram},
    {"glViewport", &t_glViewport},
    {"glBufferData", &t_glBufferData},
    {"glCompressedTexImage2D", &t_glCompressedTexImage2D},
    {"glDeleteBuffers", &t_glDeleteBuffers},
    {"glDeleteFramebuffers", &t_glDeleteFramebuffers},
    {"glDeleteRenderbuffers", &t_glDeleteRenderbuffers},
    {"glDeleteTextures", &t_glDeleteTextures},
    {"glDrawElements", &t_glDrawElements},
    {"glGetAttribLocation", &t_glGetAttribLocation},
    {"glGetUniformLocation", &t_glGetUniformLocation},
    {"glTexImage2D", &t_glTexImage2D},
    {"glUniform1iv", &t_glUniform1iv},
    {"glUniform4fv", &t_glUniform4fv},
    {"glUniformMatrix4fv", &t_glUniformMatrix4fv},
    {"glVertexAttribPointer", &t_glVertexAttribPointer},
    {"glGenBuffers", &t_glGenBuffers},
    {"glGenFramebuffers", &t_glGenFramebuffers},
    {"glGenRenderbuffers", &t_glGenRenderbuffers},
    {"glGenTextures", &t_glGenTextures},
    {"glGetFloatv", &t_glGetFloatv},
    {"glGetIntegerv", &t_glGetIntegerv},
    {"glGetProgramInfoLog", &t_glGetProgramInfoLog},
    {"glGetProgramiv", &t_glGetProgramiv},
    {"glGetShaderInfoLog", &t_glGetShaderInfoLog},
    {"glGetShaderiv", &t_glGetShaderiv},
    {"glShaderSource", &t_glShaderSource},
    {"eglDestroyContext", &t_eglDestroyContext},
    {"eglDestroySurface", &t_eglDestroySurface},
    {"eglGetDisplay", &t_eglGetDisplay},
    {"eglMakeCurrent", &t_eglMakeCurrent},
    {"eglSwapBuffers", &t_eglSwapBuffers},
    {"eglTerminate", &t_eglTerminate},
    {"eglCreateContext", &t_eglCreateContext},
    {"eglCreateWindowSurface", &t_eglCreateWindowSurface},
    {"eglGetConfigAttrib", &t_eglGetConfigAttrib},
    {"eglGetConfigs", &t_eglGetConfigs},
    {"eglInitialize", &t_eglInitialize},
    {"eglQuerySurface", &t_eglQuerySurface},
    {"AConfiguration_delete", &t_AConfiguration_delete},
    {"AConfiguration_fromAssetManager", &t_AConfiguration_fromAssetManager},
    {"AConfiguration_getCountry", &t_AConfiguration_getCountry},
    {"AConfiguration_getDensity", &t_AConfiguration_getDensity},
    {"AConfiguration_getKeyboard", &t_AConfiguration_getKeyboard},
    {"AConfiguration_getKeysHidden", &t_AConfiguration_getKeysHidden},
    {"AConfiguration_getLanguage", &t_AConfiguration_getLanguage},
    {"AConfiguration_getMcc", &t_AConfiguration_getMcc},
    {"AConfiguration_getMnc", &t_AConfiguration_getMnc},
    {"AConfiguration_getNavHidden", &t_AConfiguration_getNavHidden},
    {"AConfiguration_getNavigation", &t_AConfiguration_getNavigation},
    {"AConfiguration_getOrientation", &t_AConfiguration_getOrientation},
    {"AConfiguration_getScreenLong", &t_AConfiguration_getScreenLong},
    {"AConfiguration_getScreenSize", &t_AConfiguration_getScreenSize},
    {"AConfiguration_getSdkVersion", &t_AConfiguration_getSdkVersion},
    {"AConfiguration_getTouchscreen", &t_AConfiguration_getTouchscreen},
    {"AConfiguration_getUiModeNight", &t_AConfiguration_getUiModeNight},
    {"AConfiguration_getUiModeType", &t_AConfiguration_getUiModeType},
    {"AConfiguration_new", &t_AConfiguration_new},
    {"AInputEvent_getSource", &t_AInputEvent_getSource},
    {"AInputEvent_getType", &t_AInputEvent_getType},
    {"AKeyEvent_getAction", &t_AKeyEvent_getAction},
    {"AKeyEvent_getKeyCode", &t_AKeyEvent_getKeyCode},
    {"ALooper_pollAll", &t_ALooper_pollAll},
    {"ALooper_prepare", &t_ALooper_prepare},
    {"AMotionEvent_getAction", &t_AMotionEvent_getAction},
    {"AMotionEvent_getAxisValue", &t_AMotionEvent_getAxisValue},
    {"AMotionEvent_getPointerCount", &t_AMotionEvent_getPointerCount},
    {"AMotionEvent_getPointerId", &t_AMotionEvent_getPointerId},
    {"AMotionEvent_getX", &t_AMotionEvent_getX},
    {"AMotionEvent_getY", &t_AMotionEvent_getY},
    {"ANativeActivity_finish", &t_ANativeActivity_finish},
    {"ANativeWindow_getHeight", &t_ANativeWindow_getHeight},
    {"ANativeWindow_getWidth", &t_ANativeWindow_getWidth},
    {"ANativeWindow_setBuffersGeometry", &t_ANativeWindow_setBuffersGeometry},
    {"AStorageManager_delete", &t_AStorageManager_delete},
    {"AStorageManager_isObbMounted", &t_AStorageManager_isObbMounted},
    {"AStorageManager_new", &t_AStorageManager_new},
    {"AStorageManager_unmountObb", &t_AStorageManager_unmountObb},
    {"nv_android_init", &t_nv_android_init},
    {"AStorageManager_getMountedObbPath", &t_AStorageManager_getMountedObbPath},
    {"AStorageManager_mountObb", &t_AStorageManager_mountObb},
    {"AInputQueue_attachLooper", &t_AInputQueue_attachLooper},
    {"AInputQueue_detachLooper", &t_AInputQueue_detachLooper},
    {"AInputQueue_finishEvent", &t_AInputQueue_finishEvent},
    {"AInputQueue_getEvent", &t_AInputQueue_getEvent},
    {"AInputQueue_preDispatchEvent", &t_AInputQueue_preDispatchEvent},
    {"ALooper_addFd", &t_ALooper_addFd},
    {"__android_log_print", &t___android_log_print},
    {"FMOD_System_Create", &t_FMOD_System_Create},
    {"_ZN4FMOD5Sound11setDefaultsEfffi", &t__ZN4FMOD5Sound11setDefaultsEfffi},
    {"_ZN4FMOD5Sound19set3DMinMaxDistanceEff", &t__ZN4FMOD5Sound19set3DMinMaxDistanceEff},
    {"_ZN4FMOD5Sound7releaseEv", &t__ZN4FMOD5Sound7releaseEv},
    {"_ZN4FMOD6System13set3DSettingsEfff", &t__ZN4FMOD6System13set3DSettingsEfff},
    {"_ZN4FMOD6System14setSpeakerModeE16FMOD_SPEAKERMODE", &t__ZN4FMOD6System14setSpeakerModeE16FMOD_SPEAKERMODE},
    {"_ZN4FMOD6System16setDSPBufferSizeEji", &t__ZN4FMOD6System16setDSPBufferSizeEji},
    {"_ZN4FMOD6System17setSoftwareFormatEi17FMOD_SOUND_FORMATii18FMOD_DSP_RESAMPLER", &t__ZN4FMOD6System17setSoftwareFormatEi17FMOD_SOUND_FORMATii18FMOD_DSP_RESAMPLER},
    {"_ZN4FMOD6System19setHardwareChannelsEi", &t__ZN4FMOD6System19setHardwareChannelsEi},
    {"_ZN4FMOD6System5closeEv", &t__ZN4FMOD6System5closeEv},
    {"_ZN4FMOD6System6updateEv", &t__ZN4FMOD6System6updateEv},
    {"_ZN4FMOD6System9setOutputE15FMOD_OUTPUTTYPE", &t__ZN4FMOD6System9setOutputE15FMOD_OUTPUTTYPE},
    {"_ZN4FMOD7Channel11setPositionEjj", &t__ZN4FMOD7Channel11setPositionEjj},
    {"_ZN4FMOD7Channel11setPriorityEi", &t__ZN4FMOD7Channel11setPriorityEi},
    {"_ZN4FMOD7Channel12setFrequencyEf", &t__ZN4FMOD7Channel12setFrequencyEf},
    {"_ZN4FMOD7Channel4stopEv", &t__ZN4FMOD7Channel4stopEv},
    {"_ZN4FMOD7Channel7setModeEj", &t__ZN4FMOD7Channel7setModeEj},
    {"_ZN4FMOD7Channel9setPausedEb", &t__ZN4FMOD7Channel9setPausedEb},
    {"_ZN4FMOD7Channel9setVolumeEf", &t__ZN4FMOD7Channel9setVolumeEf},
    {"_ZN4FMOD5Sound11getDefaultsEPfS1_S1_Pi", &t__ZN4FMOD5Sound11getDefaultsEPfS1_S1_Pi},
    {"_ZN4FMOD5Sound12getOpenStateEP14FMOD_OPENSTATEPjPbS4_", &t__ZN4FMOD5Sound12getOpenStateEP14FMOD_OPENSTATEPjPbS4_},
    {"_ZN4FMOD5Sound9getLengthEPjj", &t__ZN4FMOD5Sound9getLengthEPjj},
    {"_ZN4FMOD6System10getChannelEiPPNS_7ChannelE", &t__ZN4FMOD6System10getChannelEiPPNS_7ChannelE},
    {"_ZN4FMOD6System13getDriverCapsEiPjPiP16FMOD_SPEAKERMODE", &t__ZN4FMOD6System13getDriverCapsEiPjPiP16FMOD_SPEAKERMODE},
    {"_ZN4FMOD6System13getNumDriversEPi", &t__ZN4FMOD6System13getNumDriversEPi},
    {"_ZN4FMOD6System18getChannelsPlayingEPi", &t__ZN4FMOD6System18getChannelsPlayingEPi},
    {"_ZN4FMOD6System4initEijPv", &t__ZN4FMOD6System4initEijPv},
    {"_ZN4FMOD6System9playSoundE17FMOD_CHANNELINDEXPNS_5SoundEbPPNS_7ChannelE", &t__ZN4FMOD6System9playSoundE17FMOD_CHANNELINDEXPNS_5SoundEbPPNS_7ChannelE},
    {"_ZN4FMOD7Channel11getPositionEPjj", &t__ZN4FMOD7Channel11getPositionEPjj},
    {"_ZN4FMOD7Channel11getUserDataEPPv", &t__ZN4FMOD7Channel11getUserDataEPPv},
    {"_ZN4FMOD7Channel11setUserDataEPv", &t__ZN4FMOD7Channel11setUserDataEPv},
    {"_ZN4FMOD7Channel7getModeEPj", &t__ZN4FMOD7Channel7getModeEPj},
    {"_ZN4FMOD7Channel8getIndexEPi", &t__ZN4FMOD7Channel8getIndexEPi},
    {"_ZN4FMOD7Channel9getVolumeEPf", &t__ZN4FMOD7Channel9getVolumeEPf},
    {"_ZN4FMOD7Channel9isPlayingEPb", &t__ZN4FMOD7Channel9isPlayingEPb},
    {"_ZN4FMOD6System11createSoundEPKcjP22FMOD_CREATESOUNDEXINFOPPNS_5SoundE", &t__ZN4FMOD6System11createSoundEPKcjP22FMOD_CREATESOUNDEXINFOPPNS_5SoundE},
    {"_ZN4FMOD6System12createStreamEPKcjP22FMOD_CREATESOUNDEXINFOPPNS_5SoundE", &t__ZN4FMOD6System12createStreamEPKcjP22FMOD_CREATESOUNDEXINFOPPNS_5SoundE},
    {"_ZN4FMOD6System13getDriverInfoEiPciP9FMOD_GUID", &t__ZN4FMOD6System13getDriverInfoEiPciP9FMOD_GUID},
    {"_ZN4FMOD6System23set3DListenerAttributesEiPK11FMOD_VECTORS3_S3_S3_", &t__ZN4FMOD6System23set3DListenerAttributesEiPK11FMOD_VECTORS3_S3_S3_},
    {"_ZN4FMOD7Channel15set3DAttributesEPK11FMOD_VECTORS3_", &t__ZN4FMOD7Channel15set3DAttributesEPK11FMOD_VECTORS3_},
    {"_ZN4FMOD7Channel11setCallbackEPF11FMOD_RESULTP12FMOD_CHANNEL25FMOD_CHANNEL_CALLBACKTYPEPvS5_E", &t__ZN4FMOD7Channel11setCallbackEPF11FMOD_RESULTP12FMOD_CHANNEL25FMOD_CHANNEL_CALLBACKTYPEPvS5_E},
    {"pthread_attr_init", &t_pthread_attr_init},
    {"pthread_attr_setdetachstate", &t_pthread_attr_setdetachstate},
    {"pthread_cond_broadcast", &t_pthread_cond_broadcast},
    {"pthread_cond_destroy", &t_pthread_cond_destroy},
    {"pthread_cond_init", &t_pthread_cond_init},
    {"pthread_cond_signal", &t_pthread_cond_signal},
    {"pthread_cond_wait", &t_pthread_cond_wait},
    {"pthread_join", &t_pthread_join},
    {"pthread_kill", &t_pthread_kill},
    {"pthread_mutex_destroy", &t_pthread_mutex_destroy},
    {"pthread_mutex_init", &t_pthread_mutex_init},
    {"pthread_mutex_lock", &t_pthread_mutex_lock},
    {"pthread_mutex_trylock", &t_pthread_mutex_trylock},
    {"pthread_mutex_unlock", &t_pthread_mutex_unlock},
    {"pthread_mutexattr_init", &t_pthread_mutexattr_init},
    {"pthread_mutexattr_settype", &t_pthread_mutexattr_settype},
    {"pthread_cond_timedwait", &t_pthread_cond_timedwait},
    {"pthread_create", &t_pthread_create},
    {"alarm", &t_alarm},
    {"close", &t_close},
    {"fcntl", &t_fcntl},
    {"geteuid", &t_geteuid},
    {"ioctl", &t_ioctl},
    {"lseek", &t_lseek},
    {"pipe", &t_pipe},
    {"syscall", &t_syscall},
    {"time", &t_time},
    {"usleep", &t_usleep},
    {"getenv", &t_getenv},
    {"mkdir", &t_mkdir},
    {"open", &t_open},
    {"read", &t_read},
    {"write", &t_write},
    {"writev", &t_writev},
    {"clock_gettime", &t_clock_gettime},
    {"fstat", &t_fstat},
    {"getpwuid", &t_getpwuid},
    {"gettimeofday", &t_gettimeofday},
    {"poll", &t_poll},
    {"sigaction", &t_sigaction},
    {"stat", &t_stat},
    {"socket", &t_socket},
    {"inet_aton", &t_inet_aton},
    {"inet_ntoa", &t_inet_ntoa},
    {"bind", &t_bind},
    {"connect", &t_connect},
    {"freeaddrinfo", &t_freeaddrinfo},
    {"getaddrinfo", &t_getaddrinfo},
    {"gethostbyaddr", &t_gethostbyaddr},
    {"gethostbyname", &t_gethostbyname},
    {"getpeername", &t_getpeername},
    {"getsockname", &t_getsockname},
    {"getsockopt", &t_getsockopt},
    {"recv", &t_recv},
    {"recvmsg", &t_recvmsg},
    {"select", &t_select},
    {"send", &t_send},
    {"sendmsg", &t_sendmsg},
    {"setsockopt", &t_setsockopt},
};

const std::size_t kThunkTableSize = sizeof(kThunkTable) / sizeof(kThunkTable[0]);

}  // namespace wb
